<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fannoise" nsURI="http://www.airbus.com.generic/fannoise" nsPrefix="fannoise">
  <eClassifiers xsi:type="ecore:EClass" name="FanNoiseProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflow" eType="ecore:EClass ananax.ecore#//Workflow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thermodynamicConditions"
        upperBound="-1" eType="ecore:EClass ananax.ecore#//ThermodynamicCondition"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
